# Generated by Django 6.0 on 2026-01-29 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_code', models.CharField(max_length=10, unique=True, verbose_name='کدملی')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=30, verbose_name='نام خانوادگی ')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('address', models.TextField(verbose_name='ادرس ')),
                ('hire_data', models.DateField(verbose_name='تاریخ استخدام')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت اشتغال ')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='عکس پرسنلی ')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=30, verbose_name=' مقطع تحصیلی ')),
                ('field_of_study', models.CharField(max_length=50, verbose_name='رشته تحصیلی ')),
                ('university', models.CharField(max_length=50, verbose_name='دانشگاه ')),
                ('graduation_year', models.IntegerField(verbose_name='سال فارغ التحصیلی')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='کارمند ')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, verbose_name='پلاک خودرو')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='کارمند')),
            ],
        ),
    ]
