# Generated by Django 6.0 on 2026-02-10 11:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='hire_data',
        ),
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default=datetime.date(2026, 2, 10), help_text='تاریخ استخدام را به فرمت میلادی وارد کنید (YYYY-MM-DD)', verbose_name='تاریخ استخدام'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=50, verbose_name='مقطع تحصیلی'),
        ),
        migrations.AlterField(
            model_name='education',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(max_length=100, verbose_name='رشته تحصیلی'),
        ),
        migrations.AlterField(
            model_name='education',
            name='graduation_year',
            field=models.IntegerField(verbose_name='سال فارغ\u200cالتحصیلی'),
        ),
        migrations.AlterField(
            model_name='education',
            name='university',
            field=models.CharField(max_length=100, verbose_name='دانشگاه'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='national_code',
            field=models.CharField(max_length=10, unique=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employees/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(help_text='سه رقم آخر پلاک را وارد کنید', max_length=3, unique=True, verbose_name='پلاک خودرو'),
        ),
    ]
